#!/usr/bin/env bash

if [[ -s "/home/pulse/.rvm/environments/ree-1.8.7-2011.03" ]]
then
  source "/home/pulse/.rvm/environments/ree-1.8.7-2011.03"
  exec ri "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/pulse/.rvm/environments/ree-1.8.7-2011.03'" >&2
  exit 1
fi
  