#!/usr/bin/env bash

if [[ -s "/home/pulse/.rvm/environments/ruby-1.9.2-p290" ]]
then
  source "/home/pulse/.rvm/environments/ruby-1.9.2-p290"
  exec testrb "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/pulse/.rvm/environments/ruby-1.9.2-p290'" >&2
  exit 1
fi
  